export const RESULT_TRUE = 'RESULT_TRUE';
export const RESULT_FALSE = 'RESULT_FALSE';
export const RESULT_PLANET = 'RESULT_PLANET';
export const RESULT_FILTER_TYPE = 'RESULT_FILTER_TYPE';
export const RESULT_ALL_FILTERS = 'RESULT_ALL_FILTERS';
export const RESULT_DATA_FILTERED = 'RESULT_DATA_FILTERED';
//export const RESULT_SEARCH_FILTER = 'RESULT_SEARCH_FILTER';
//export const RESULT_CLEAR_FILTER = 'RESULT_CLEAR_FILTER';
